# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0675d8fafd10b22e123e07121d9e2184663ecbb6ab366771210786bc2270ae9dd7de8dc66ef5825cf46bb261e4c0aecd82f86ec41df652b60f324010164a9bef

test:
  secret_key_base: ab33c078fc8235f273a0b7d2f958b4119c9e2af38a813533958e52ffb00b535d3d142145840a2988eaab2d50ac3889bbdc631ca259ec6f982c389df2f54c4a22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
